### ISSUE TITLE
SMPP Server error

### ISSUE THREAD

**Issue by ankit22550** [tiltroom/fakesmpp#4]
Hello Team,  

i just install SMPP server using docker but getting below error after start.

yarn run v1.22.4
$ node smpp.js --port=2775 --ddmin=5000 --ddmax=15000
{"timestamp":"Fri, 30 Oct 2020 12:21:09 GMT","message":"Server listen port #2775","level":"info"}
events.js:174
      throw er; // Unhandled 'error' event
      ^

RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds
    at boundsError (internal/buffer.js:47:11)
    at Buffer.readUInt32BE (internal/buffer.js:268:5)
    at Function.PDU.fromStream (/usr/src/app/node_modules/smpp/lib/pdu.js:48:30)
    at Session._extractPDUs (/usr/src/app/node_modules/smpp/lib/smpp.js:59:20)
    at Socket.emit (events.js:198:13)
    at emitReadable_ (_stream_readable.js:555:12)
    at onEofChunk (_stream_readable.js:532:7)
    at readableAddChunk (_stream_readable.js:237:5)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:125:12)
Emitted 'error' event at:
    at Session._extractPDUs (/usr/src/app/node_modules/smpp/lib/smpp.js:63:9)
    at Socket.emit (events.js:198:13)
    [... lines matching original stack trace ...]
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:125:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by tiltroom** [comment]
Hey sorry,
I didn't notice there was an open issue as I hardly ever use this as a testing tool.

I have revamped it to use ENV instead of cli params and is targeted to run on node16.
I'll update the readme soon.
